gateway:
  services:
    auction: http://auction-service:8082
    payment: http://payment-service:8081
    notification: http://notification-service:8080
    analytics: http://analytics-service:8085
server:
  port: 8080

gateway:
  services:
    auction: http://auction-service:8080
    payment: http://payment-service:8080
    notification: http://notification-service:8080
    analytics: http://analytics-service:8080
