---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: auction-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auction-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auction-db
  template:
    metadata:
      labels:
        app: auction-db
    spec:
      containers:
        - name: postgres
          image: postgres:15
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "auction_db"
            - name: POSTGRES_USER
              value: "auction_user"
            - name: POSTGRES_PASSWORD
              value: "auction_pass"
          volumeMounts:
            - name: auction-db-storage
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: auction-db-storage
          persistentVolumeClaim:
            claimName: auction-db-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: auction-db
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: auction-db
