---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-service
  template:
    metadata:
      labels:
        app: notification-service
    spec:
      containers:
        - name: notification-service
          image: apibp-20242yb-team-01-notification-service:dev
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: SMTP_USERNAME
              value: "yourExample@gmail.com"
            - name: SMTP_PASSWORD
              value: "password"
            - name: SMTP_FROM
              value: "yourExample@gmail.com"
            - name: RABBITMQ_URL
              value: amqp://guest:guest@rabbitmq:5672
            - name: QUEUE_BINDINGS
              value: payment.locked,payment.success,payment.failed,auction.winner,auction.seller
            - name: SMTP_HOST
              value: smtp.gmail.com
            - name: SMTP_PORT
              value: "587"
            - name: OPENSEARCH_HOST
              value: http://opensearch-node1:9200
            - name: OPENSEARCH_USERNAME
              value: admin
            - name: OPENSEARCH_PASSWORD
              value: quartz_EB_@5911
---
apiVersion: v1
kind: Service
metadata:
  name: notification-service
spec:
  selector:
    app: notification-service
  ports:
    - port: 8080
      targetPort: 8080
